name: fluent_gpt
description: A crossplatform gpt project created with Flutter.
publish_to: "none"
version: 1.0.3+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.8.7
  system_theme: ^3.0.0
  flutter_acrylic: ^1.1.3
  go_router: ^14.0.1
  provider: ^6.1.1
  url_launcher: ^6.3.0
  window_manager: ^0.4.2
  shared_preferences: ^2.2.2
  chat_gpt_flutter: ^1.0.16
  tray_manager: ^0.2.3
  hotkey_manager: ^0.2.3
  process_run: ^1.1.0
  shell: ^2.0.0
  file: ^6.1.4
  markdown_widget: ^2.3.2+6
  fluentui_system_icons: ^1.1.246
  rxdart: ^0.28.0
  dio: ^5.4.0
  windows_single_instance: ^1.0.1
  flutter_highlighter: ^0.1.1
  file_picker: ^8.0.3
  cross_file: ^0.3.4+1
  mime_type: ^1.0.0
  pasteboard: ^0.3.0
  easy_image_viewer: ^1.4.1
  path_provider: ^2.1.3
  protocol_handler: ^0.2.0
  package_info_plus: ^8.0.0
  flutter_gpt_tokenizer: ^0.1.1
  super_drag_and_drop: ^0.8.17
  file_selector: ^1.0.3
  super_clipboard: ^0.8.17
  permission_handler: ^11.3.1
  http: ^1.2.1
  animated_list_plus: ^0.5.2
  scroll_to_index: ^3.0.1
  nanoid2: ^2.0.1
  widget_and_text_animator: ^1.1.5
  simple_animations: ^5.0.2
  flutter_moving_background: ^0.0.5
  smooth_page_indicator: ^1.2.0+3
  adaptive_layout: ^0.1.7
  flutter_local_notifications: ^17.2.1+2
  cryptography: ^2.7.0
  cryptography_flutter: ^2.3.2
  keypress_simulator: ^0.2.0
  langchain: ^0.7.5
  langchain_openai: ^0.7.1
  langchain_ollama: ^0.3.1
  html: ^0.15.4
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  google_sign_in: ^6.2.1
  glowy_borders: ^1.0.2
  system_info2: ^4.0.0
  intl: ^0.19.0
  entry: ^1.0.0
  record: ^5.1.2
  deepgram_speech_to_text: ^2.3.2
  audioplayers: ^6.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  intl: ^0.19.0
  uuid: ^4.1.0

flutter:
  assets:
    - assets/
  uses-material-design: true