name: fluent_gpt
description: A crossplatform gpt project created with Flutter.
publish_to: "none"
version: 0.9.15+15

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.8.7
  system_theme: ^3.0.0
  flutter_acrylic: ^1.1.3
  go_router: ^14.0.1
  provider: ^6.1.1
  url_launcher: ^6.3.0
  window_manager: ^0.3.9
  # chat_gpt_sdk: ^3.0.7
  shared_preferences: ^2.2.2
  chat_gpt_flutter: ^1.0.16
  # system_tray: ^2.0.3
  tray_manager: ^0.2.3
  hotkey_manager: ^0.2.3
  process_run: ^1.1.0
  shell: ^2.0.0
  file: ^6.1.4
  markdown_widget: ^2.3.2+6
  fluentui_system_icons: ^1.1.246
  rxdart: ^0.28.0
  dio: ^5.4.0
  windows_single_instance: ^1.0.1
  flutter_highlighter: ^0.1.1
  file_picker: ^8.0.3
  background_downloader: ^8.4.0
  cross_file: ^0.3.4+1
  mime_type: ^1.0.0
  pasteboard: ^0.2.0
  easy_image_viewer: ^1.4.1
  path_provider: ^2.1.3
  protocol_handler: ^0.2.0
  package_info_plus: ^8.0.0
  flutter_gpt_tokenizer: ^0.1.1
  super_drag_and_drop: ^0.8.17
  file_selector: ^1.0.3
  super_clipboard: ^0.8.17
  permission_handler: ^11.3.1
  http: ^1.2.1
  animated_list_plus: ^0.5.2
  scrollable_positioned_list: ^0.3.8
  nanoid2: ^2.0.1
  widget_and_text_animator: ^1.1.5
  simple_animations: ^5.0.2
  flutter_moving_background: ^0.0.5
  smooth_page_indicator: ^1.2.0+3
  adaptive_layout: ^0.1.7
  flutter_local_notifications: ^17.2.1+2
  cryptography: ^2.7.0
  cryptography_flutter: ^2.3.2
  keypress_simulator: ^0.2.0
  langchain: ^0.5.0+1
  langchain_openai: ^0.5.0+1
  langchain_ollama: ^0.1.0
  html: ^0.15.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  msix: ^3.16.7
  change_app_package_name: ^1.3.0
  flutter_launcher_icons: "^0.13.1"

dependency_overrides:
  intl: ^0.19.0
  uuid: ^4.1.0


flutter:
  assets:
    - assets/
  uses-material-design: true

flutter_launcher_icons:
  android: false
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"


msix_config:
  display_name: Fluent GPT
  publisher_display_name: Realkalash
  msix_version: 0.8.0.0
  logo_path: C:\Users\realk\repos\pet\fluent_gpt\assets\app_icon.png
  capabilities: internetClient, microphone
  languages: en-us
  protocol_activation: fluentgpt
  app_installer:
    publish_folder_path: msi_flutter_builds
    hours_between_update_checks: 0
    automatic_background_task: false
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: false