class CitiesList {
  static List<String> getAllCitiesList() {
    return [
      ...valueAllBigAmerica,
      ...valueAllBigCanada,
      ...valueAllBigChina,
      ...valueAllBigJapan,
      ...valueAllBigUkraine,
      ...valueAllBigRussia,
    ];
  }

  static const valueAllBigAmerica = [
    'New York',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Phoenix',
    'Philadelphia',
    'San Antonio',
    'San Diego',
    'Dallas',
    'San Jose',
    'Austin',
    'Jacksonville',
    'San Francisco',
    'Indianapolis',
    'Columbus',
    'Fort Worth',
    'Charlotte',
    'Seattle',
    'Denver',
    'El Paso',
    'Detroit',
    'Washington',
    'Boston',
    'Memphis',
    'Nashville',
    'Portland',
    'Oklahoma City',
    'Las Vegas',
    'Baltimore',
    'Louisville',
    'Milwaukee',
    'Albuquerque',
    'Tucson',
    'Fresno',
    'Sacramento',
    'Mesa',
    'Kansas City',
    'Atlanta',
    'Long Beach',
    'Colorado Springs',
    'Raleigh',
    'Miami',
    'Virginia Beach',
    'Omaha',
    'Oakland',
    'Minneapolis',
    'Tulsa',
    'Arlington',
    'New Orleans',
    'Wichita',
    'Cleveland',
    'Tampa',
    'Bakersfield',
    'Aurora',
    'Honolulu',
    'Anaheim',
    'Santa Ana',
    'Corpus Christi',
    'Riverside',
    'St. Louis',
    'Lexington',
    'Pittsburgh',
    'Stockton',
    'Anchorage',
    'Cincinnati',
    'Saint Paul',
    'Greensboro',
    'Toledo',
    'Newark',
    'Plano',
    'Henderson',
    'Lincoln',
    'Orlando',
    'Jersey City',
    'Chula Vista',
    'Buffalo',
    'Fort Wayne',
    'Chandler',
    'St. Petersburg',
    'Laredo',
    'Durham',
    'Irvine',
    'Madison',
    'Norfolk',
    'Lubbock',
    'Gilbert',
    'Winston–Salem',
    'Glendale',
    'Reno',
    'Hialeah',
    'Garland',
    'Chesapeake',
    'Irving',
    'North Las Vegas',
    'Scottsdale',
    'Baton Rouge',
    'Fremont',
    'Richmond',
    'Boise',
    'San Bernardino',
    'Spokane',
    'Birmingham',
    'Modesto',
    'Des Moines',
    'Rochester',
    'Tacoma',
    'Fontana',
  ];
  static const valueAllBigCanada = [
    'Toronto',
    'Montreal',
    'Calgary',
    'Ottawa',
    'Edmonton',
    'Mississauga',
    'Winnipeg',
    'Vancouver',
    'Brampton',
    'Hamilton',
    'Quebec City',
    'Surrey',
    'Laval',
    'Halifax',
    'London',
    'Markham',
    'Vaughan',
    'Gatineau',
    'Longueuil',
    'Burnaby',
    'Saskatoon',
    'Kitchener',
    'Windsor',
    'Regina',
    'Richmond',
    'Richmond Hill',
    'Oakville',
    'Burlington',
    'Greater Sudbury',
    'Sherbrooke',
    'Oshawa',
    'Saguenay',
    'Lévis',
    'Barrie',
    'Abbotsford',
    'Coquitlam',
    'Trois-Rivières',
    'St. Catharines',
    'Guelph',
    'Cambridge',
    'Whitby',
    'Kelowna',
    'Kingston',
    'Ajax',
    'Langley',
    'Saanich',
    'Terrebonne',
    'Milton',
    'St. John\'s',
    'Thunder Bay',
    'Waterloo',
    'Delta',
    'Chatham-Kent',
    'Red Deer',
    'Strathcona County',
    'Brantford',
    'Saint-Jean-sur-Richelieu',
    'Cape Breton',
    'Lethbridge',
    'Clarington',
    'Pickering',
    'Nanaimo',
    'Kamloops',
    'Niagara Falls',
    'Victoria',
    'Brossard',
    'Repentigny',
    'Newmarket',
    'Chilliwack',
    'Maple Ridge',
    'Peterborough',
    'Kawartha Lakes',
    'Drummondville',
    'Saint-Jérôme',
    'Prince George',
    'Sault Ste. Marie',
    'Moncton',
    'Sarnia',
    'Wood Buffalo',
    'New Westminster',
    'Châteauguay',
    'Caledon',
    'Saint John',
    'Norfolk County',
    'Drummond/North Elmsley',
    'Stratford',
    'Orillia',
    'Sherwood Park',
    'Lévis',
    'Saint-Hyacinthe',
    'Saint-Hubert',
  ];
  static const valueAllBigChina = [
    'Shanghai',
    'Beijing',
    'Tianjin',
    'Guangzhou',
    'Shenzhen',
    'Wuhan',
    'Dongguan',
    'Chongqing',
    'Chengdu',
    'Nanjing',
    'Nanchong',
    'Xi\'an',
  ];
  static const valueAllBigJapan = [
    'Tokyo',
    'Yokohama',
    'Osaka',
    'Nagoya',
    'Sapporo',
    'Fukuoka',
    'Kobe',
    'Kyoto',
    'Kawasaki',
    'Saitama',
    'Hiroshima',
    'Sendai',
    'Kitakyushu',
    'Chiba',
  ];
  static const valueAllBigUkraine = [
    'Kyiv',
    'Kharkiv',
    'Odesa',
    'Dnipro',
    'Donetsk',
    'Zaporizhzhia',
    'Lviv',
    'Kryvyi Rih',
    'Mykolaiv',
    'Mariupol',
    'Luhansk',
    'Vinnytsia',
    'Makiivka',
    'Simferopol',
    'Kherson',
    'Poltava',
    'Chernihiv',
    'Cherkasy',
    'Sumy',
    'Zhytomyr',
    'Horlivka',
    'Rivne',
    'Kamianske',
    'Kropyvnytskyi',
    'Chernivtsi',
    'Ternopil',
    'Kremenchuk',
    'Lutsk',
    'Ivano-Frankivsk',
    'Bila Tserkva',
    'Kramatorsk',
    'Melitopol',
    'Kerch',
    'Uzhhorod',
    'Berdiansk',
    'Nikopol',
    'Sloviansk',
    'Brovary',
    'Khartsyzk',
  ];
  static const valueAllBigRussia = [
    'Moscow',
    'Saint Petersburg',
    'Novosibirsk',
    'Yekaterinburg',
    'Nizhny Novgorod',
    'Samara',
    'Omsk',
    'Kazan',
    'Chelyabinsk',
    'Rostov-on-Don',
    'Ufa',
    'Volgograd',
    'Perm',
    'Krasnoyarsk',
    'Voronezh',
    'Saratov',
    'Krasnodar',
    'Tolyatti',
    'Izhevsk',
    'Ulyanovsk',
    'Barnaul',
    'Vladivostok',
    'Yaroslavl',
    'Irkutsk',
    'Tyumen',
    'Khabarovsk',
    'Orenburg',
    'Novokuznetsk',
    'Kemerovo',
    'Ryazan',
    'Astrakhan',
    'Naberezhnye Chelny',
    'Penza',
    'Lipetsk',
    'Tula',
    'Kirov',
    'Cheboksary',
    'Kaliningrad',
    'Bryansk',
    'Smolensk',
    'Tver',
    'Magnitogorsk',
    'Kurgan',
    'Makhachkala',
    'Surgut',
    'Orsk',
    'Nizhnevartovsk',
    'Nizhnekamsk',
    'Volzhsky',
    'Taganrog',
    'Engels',
    'Blagoveshchensk',
    'Severodvinsk',
    'Kostroma',
    'Arzamas',
    'Kovrov',
    'Novomoskovsk',
    'Shakhty',
    'Neftekamsk',
    'Nefteyugansk',
    'Kislovodsk',
    'Novocherkassk',
    'Derbent',
    'Kamyshin',
    'Pyatigorsk',
    'Balakovo',
    'Zheleznogorsk',
    'Kyzyl',
    'Abakan',
    'Norilsk',
    'Rubtsovsk',
    'Kyzyl',
    'Abakan',
    'Norilsk',
  ];
}
