import 'package:fluentui_system_icons/fluentui_system_icons.dart';
import 'package:flutter/widgets.dart';

const Map<String, IconData> tagToIconMap = {
  'chat': FluentIcons.chat_24_filled,
  'home': FluentIcons.home_24_filled,
  'cloud': FluentIcons.cloud_24_filled,
  'align_bottom': FluentIcons.align_bottom_24_filled,
  'app_folder': FluentIcons.app_folder_24_filled,
  'app_generic': FluentIcons.app_generic_24_filled,
  'archive': FluentIcons.archive_24_filled,
  'arrow_routing': FluentIcons.arrow_routing_24_filled,
  'book_question_mark': FluentIcons.book_question_mark_24_filled,
  'edit': FluentIcons.edit_24_filled,
  'text_grammar_wand': FluentIcons.text_grammar_wand_24_filled,
  'translate': FluentIcons.translate_24_filled,
  'local_language': FluentIcons.local_language_24_filled,
  'access_time': FluentIcons.access_time_24_filled,
  'accessibility': FluentIcons.accessibility_24_filled,
  'accessibility_checkmark': FluentIcons.accessibility_checkmark_24_filled,
  'accessibility_error': FluentIcons.accessibility_error_24_filled,
  'accessibility_more': FluentIcons.accessibility_more_24_filled,
  'accessibility_question_mark':
      FluentIcons.accessibility_question_mark_24_filled,
  'add': FluentIcons.add_24_filled,
  'add_circle': FluentIcons.add_circle_24_filled,
  'add_square': FluentIcons.add_square_24_filled,
  'add_square_multiple': FluentIcons.add_square_multiple_24_filled,
  'add_subtract_circle': FluentIcons.add_subtract_circle_24_filled,
  'airplane': FluentIcons.airplane_24_filled,
  'airplane_landing': FluentIcons.airplane_landing_24_filled,
  'airplane_take_off': FluentIcons.airplane_take_off_24_filled,
  'album': FluentIcons.album_24_filled,
  'album_add': FluentIcons.album_add_24_filled,
  'alert': FluentIcons.alert_24_filled,
  'alert_badge': FluentIcons.alert_badge_24_filled,
  'alert_off': FluentIcons.alert_off_24_filled,
  'alert_on': FluentIcons.alert_on_24_filled,
  'alert_snooze': FluentIcons.alert_snooze_24_filled,
  'alert_urgent': FluentIcons.alert_urgent_24_filled,
  'align_center_horizontal': FluentIcons.align_center_horizontal_24_filled,
  'align_center_vertical': FluentIcons.align_center_vertical_24_filled,
  'align_left': FluentIcons.align_left_24_filled,
  'align_right': FluentIcons.align_right_24_filled,
  'animal_cat': FluentIcons.animal_cat_24_filled,
  'attach': FluentIcons.attach_24_filled,
  'autosum': FluentIcons.autosum_24_filled,
  'beaker': FluentIcons.beaker_24_filled,
  'bed': FluentIcons.bed_24_filled,
  'board': FluentIcons.board_24_filled,
  'book': FluentIcons.book_24_filled,
  'bookmark': FluentIcons.bookmark_24_filled,
  'bowl_chopsticks': FluentIcons.bowl_chopsticks_24_filled,
  'box': FluentIcons.box_24_filled,
  'bot_sparkle': FluentIcons.bot_sparkle_24_filled,
  'braces': FluentIcons.braces_24_filled,
  'branch': FluentIcons.branch_24_filled,
  'briefcase': FluentIcons.briefcase_24_filled,
  'bug': FluentIcons.bug_24_filled,
  'building': FluentIcons.building_24_filled,
  'calculator': FluentIcons.calculator_24_filled,
  'calendar': FluentIcons.calendar_24_filled,
  'call': FluentIcons.call_24_filled,
  'chess': FluentIcons.chess_20_filled,
  'clipboard': FluentIcons.clipboard_24_filled,
};

IconData? getIconForTag(String tag) {
  return tagToIconMap[tag];
}
