import 'dart:developer';

import 'package:fluent_gpt/common/prefs/app_cache.dart';
import 'package:fluent_ui/fluent_ui.dart';
import 'package:flutter/foundation.dart';
import 'package:rxdart/rxdart.dart';

BehaviorSubject<Map<String, String?>> currentLocalization =
    BehaviorSubject.seeded(I18n._localizations['en']!);
BehaviorSubject<Locale> localeSubject = BehaviorSubject<Locale>();

class I18n {
  // get stream
  static Stream<Map<String, String?>> get currentLocalizationStream =>
      currentLocalization.stream;

  //get current locale
  static Locale get currentLocale => localeSubject.value;
  static void init() {
    final localeCache = AppCache.locale.value;
    if (localeCache == null) {
      localeSubject.add(Locale('en'));
    } else {
      localeSubject.add(Locale(localeCache));
    }
    if (kDebugMode) {
      log('init I18n: $localeCache');
      final loc = _localizations[localeCache]!;
      currentLocalization.add(loc);
    }
    localeSubject.listen((locale) {
      final localizations = _localizations[locale.languageCode]!;
      currentLocalization.add(localizations);
    });
  }

  static const Map<String, Map<String, String?>> _localizations = {
    'en': {
      'app_name': 'Fluent GPT',
      'WELCOME!': null,
      'Access Granted': null,
      'Grant Access': null,
      'Configure your AI': null,
      'We will ask for some permissions to make sure you have the best experience':
          null,
      'Configure your AI to work as you want': null,
      'Add your models': null,
      'Add': null,
      'Permissions': null,
      'Granting these permissions ensures all features work seamlessly from the get-go.':
          null,
      'Files and Folders': null,
      'Allows you to save chats history and temprorarily python files generated by LLM':
          null,
      'Microphone': null,
      'Allows you to record your voice and send it to LLM': null,
      'Accessibility': null,
      'Allows you to use overlay, resize windows and more.': null,
      'Notifications': null,
      'Allows you to receive notifications from the app.': null,
      'Create new chat (only in chat)': null,
      'Escape/Cancel selection (only in chat)': null,
      'Reset chat (only in chat)': null,
      'Copy last message to clipboard (only in chat)': null,
      'Include current chat history in conversation': null,
      'Search in chat (only when input field is focused)': null,
      'Open/Focus/Hide window': null,
      'Show overlay for selected text': null,
      'Shortcuts': null,
      'This is your quick shortcuts you can use anytime': null,
      'Continue': null,
      'Edit prompt': null,
      'edit_prompt_dialog_helper': '''Helpers:
\${lang} - the language of the selected text
\${clipboardAccess} - if you want to enable the clipboard access for LLM
\${input} - the selected text''',
      'Title:': null,
      'Icon:': null,
      'Generate a 3-5 words title based on this prompt: "{{input}}"': null,
      'Prompt:': null,
      'Add data to prompt:': null,
      'User input': null,
      'Current language': null,
      'Clipboard access': null,
      'Info about user': null,
      'Timestamp': null,
      'System info': null,
      'Tags (Use ; to separate tags)': null,
      'Tags': null,
      'Do not show the main window after the prompt is run. The result will be shown in a push notification.\nUseful when you just want to copy the result to clipboard':
          null,
      'Silent': null,
      'If checked, the prompt will include system prompt with each activation':
          null,
      'Include System Prompt': null,
      'If checked, the prompt will include ALL messages from the conversation with each activation':
          null,
      'Show in chat field': null,
      'Show in context menu': null,
      'Show in home page': null,
      'Show in overlay': null,
      'Keybinding:': null,
      'Set keybinding': null,
      'Apply': null,
      'Add sub-prompt list': null,
      'Close': null,
      'Conversation style': null,
      'Conversation length': null,
      'API token is empty!': null,
      'When you send a message, the app will use the system message along with your prompt. This value may differ from your own calculations because some additional information can be sent with each of your prompts.\nTotal is the total tokens that exists in current chat\nSent is the total tokens that you have sent\nReceived is the total tokens that you have received':
          null,
      'sent:': null,
      'received:': null,
      'Text size': null,
      'Include conversation': null,
      'Add system message': null,
      'Capture screenshot': null,
      'You need to obtain Brave API key to use web search': null,
      'Settings->API and URLs': null,
      'Disable web search': null,
      'Enable web search': null,
      'To prevent token overflows unnecessary cost we propose to limit the conversation length':
          null,
      'Max tokens to include': null,
      'Min': null,
      'Med': null,
      'Hight': null,
      'Max': null,
      'Select items to include in system prompt': null,
      'Knowledge about user': null,
      'City name': null,
      'Weather': null,
      'User name': null,
      'Current timestamp': null,
      'OS info': null,
      'Summarize conversation and populate the knowledge about the user': null,
      'Use memory about the user': null,
      'Auto play messages from ai': null,
      'Will ask AI to produce buttons for each response. It will consume additional tokens in order to generate suggestions':
          null,
      'Do you want to enable suggestion helpers?': null,
      'Enable': null,
      'No. Don\'t show again': null,
      'Choose code block': null,
      'Dismiss': null,
      'Use "/" for commands or type your message here': null,
      'Settings': null,
      'General': null,
      'Appearance': null,
      'Tools': null,
      'User info': null,
      'API and URLs': null,
      'On response': null,
      'Quick prompts': null,
      'Overlay': null,
      'Storage': null,
      'Hotkeys': null,
      'About': null,
      'Open the window keybinding': null,
      'Open the window': null,
      'Take a screenshot keybinding': null,
      'Use visual AI': null,
      '[Not set]': null,
      'Push-to-talk with screenshot': null,
      'Push-to-talk': null,
      'Show all keybindings': null,
      'Application storage location': null,
      'Delete temp cache? Size:': null,
      'Clear all data': null,
      'Overlay settings': null,
      'Enable overlay': null,
      'Show settings icon in overlay': null,
      'Adaptive': null,
      'Show suggestions after ai response': null,
      'Brave API key (search engine) \$': null,
      'Text-to-Speech service:': null,
      'Global system prompt': null,
      'Customizable Global system prompt will be used for all NEW chats. To check the whole system prompt press button below':
          null,
      'Click here to check the whole system prompt': null,
      'Use ai to name chat': null,
      'Can cause additional charges!': null,
      'Audio and Microphone': null,
      'Locale': null,
      'Launch at startup': null,
      'Prevent close app': null,
      'Show app in dock': null,
      'Hide window title': null,
      'User city': null,
      'Your name that will be used in the chat': null,
      'Your city name that will be used in the chat and to get weather': null,
      'Include knowledge about user': null,
      'Open info about User': null,
      'Include user city name in system prompt': null,
      'Include weather in system prompt': null,
      'Include user name in system prompt': null,
      'Include current date and time in system prompt': null,
      'Include system info in system prompt': null,
      'Learn about the user after creating new chat \$\$': null,
      'Function tools \$\$': null,
      'Toggle All': null,
      'Auto copy to clipboard': null,
      'Auto open url': null,
      'Generate images': null,
      'Additional tools': null,
      'Imgur (Used to upload your image to your private Imgur account and get image link)':
          null,
      'Image Search engines': null,
      'Enable annoy mode': null,
      'Use timer and allow AI to write you. Can cause additional charges!':
          null,
      'Accent Color': null,
      'Theme mode': null,
      'Light': null,
      'Dark': null,
      'Background': null,
      'Use aero': null,
      'Use acrylic': null,
      'Use transparent': null,
      'Use mica': null,
      'Transparency': null,
      'Set window as frameless': null,
      'Restart the app to apply changes': null,
      'Message Text size': null,
      'Basic Message Text Size': null,
      'Compact Message Text Size': null,
      'Voice:': null,
      'Read sample': null,
      'Weather in': null,
      'More': null,
      'Edit': null,
      'Continue writing': null,
      'Explain this': null,
      'Summarize this': null,
      'Check grammar': null,
      'Improve writing': null,
      'Translate': null,
      'Answer with tags': null,
      'Search': null,
      'Chat rooms': null,
      'Create new chat': null,
      'Create folder': null,
      'Deleted chats': null,
      'Storage usage': null,
      'Refresh from disk': null,
      'Add new': null,
    },
    'ru': {
      'app_name': 'Fluent GPT',
      'WELCOME!': 'ДОБРО ПОЖАЛОВАТЬ!',
      'Access Granted': 'Доступ предоставлен',
      'Grant Access': 'Предоставить доступ',
      'Configure your AI': 'Настройте ваш ИИ',
      'We will ask for some permissions to make sure you have the best experience':
          'Мы попросим некоторые разрешения, чтобы обеспечить вам лучший опыт',
      'Configure your AI to work as you want':
          'Настройте ваш ИИ так, как вы хотите',
      'Add your models': 'Добавьте свои модели',
      'Add': 'Добавить',
      'Permissions': 'Разрешения',
      'Granting these permissions ensures all features work seamlessly from the get-go.':
          'Предоставление этих разрешений обеспечивает бесперебойную работу всех функций с самого начала.',
      'Files and Folders': 'Файлы и папки',
      'Allows you to save chats history and temprorarily python files generated by LLM':
          'Позволяет сохранять историю чатов и временные файлы python, созданные LLM',
      'Microphone': 'Микрофон',
      'Allows you to record your voice and send it to LLM':
          'Позволяет записывать ваш голос и отправлять его в LLM',
      'Accessibility': 'Доступность',
      'Allows you to use overlay, resize windows and more.':
          'Позволяет использовать наложение, изменять размер окон и многое другое.',
      'Notifications': 'Уведомления',
      'Allows you to receive notifications from the app.':
          'Позволяет получать уведомления от приложения.',
      'Create new chat (only in chat)': 'Создать новый чат (только в чате)',
      'Escape/Cancel selection (only in chat)':
          'Выход/Отмена выбора (только в чате)',
      'Reset chat (only in chat)': 'Сбросить чат (только в чате)',
      'Copy last message to clipboard (only in chat)':
          'Скопировать последнее сообщение в буфер обмена (только в чате)',
      'Include current chat history in conversation':
          'Включить текущую историю чата в разговор',
      'Search in chat (only when input field is focused)':
          'Поиск в чате (только когда поле ввода в фокусе)',
      'Open/Focus/Hide window': 'Открыть/Сфокусировать/Скрыть окно',
      'Show overlay for selected text':
          'Показать наложение для выбранного текста',
      'Shortcuts': 'Ярлыки',
      'This is your quick shortcuts you can use anytime':
          'Это ваши быстрые ярлыки, которые вы можете использовать в любое время',
      'Continue': 'Продолжить',
      'Edit prompt': 'Редактировать промпт',
      'edit_prompt_dialog_helper': '''Помощники:
\${lang} - Текущий язык
\${clipboardAccess} - если вы хотите включить доступ к буферу обмена для LLM
\${input} - выбранный текст''',
      'Title:': 'Заголовок:',
      'Icon:': 'Иконка:',
      'Generate a 3-5 words title based on this prompt: "{{input}}"':
          'Сгенерируйте заголовок из 3-5 слов на основе этого промпта: "{{input}}"',
      'Prompt:': 'Промпт:',
      'Add data to prompt:': 'Добавить данные к промпту:',
      'User input': 'Ввод пользователя',
      'Current language': 'Текущий язык',
      'Clipboard access': 'Доступ к буферу обмена',
      'Info about user': 'Информация о пользователе',
      'Timestamp': 'Метка времени',
      'System info': 'Информация о системе',
      'Tags (Use ; to separate tags)':
          'Теги (используйте ; для разделения тегов)',
      'Tags': 'Теги',
      'Do not show the main window after the prompt is run. The result will be shown in a push notification.\nUseful when you just want to copy the result to clipboard':
          'Не показывать главное окно после выполнения промпта. Результат будет показан в push-уведомлении.\nПолезно, когда вы просто хотите скопировать результат в буфер обмена',
      'Silent': 'Тихий',
      'If checked, the prompt will include system prompt with each activation':
          'Если отмечено, промпт будет включать сис промпт при каждом активации',
      'Include System Prompt': 'Включить системный промпт',
      'If checked, the prompt will include ALL messages from the conversation with each activation':
          'Если отмечено, промпт будет включать ВСЕ сообщения из разговора при каждом активации',
      'Show in chat field': 'Показать в поле чата',
      'Show in context menu': 'Показать в контекстном меню',
      'Show in home page': 'Показать на главной странице',
      'Show in overlay': 'Показать в наложении',
      'Keybinding:': 'Привязка клавиш:',
      'Set keybinding': 'Установить привязку клавиш',
      'Apply': 'Применить',
      'Add sub-prompt list': 'Добавить список суб-промптов',
      'Close': 'Закрыть',
      'Conversation style': 'Стиль разговора',
      'Conversation length': 'Длина разговора',
      'API token is empty!': 'Токен API пуст!',
      'When you send a message, the app will use the system message along with your prompt. This value may differ from your own calculations because some additional information can be sent with each of your prompts.\nTotal is the total tokens that exists in current chat\nSent is the total tokens that you have sent\nReceived is the total tokens that you have received':
          'Когда вы отправляете сообщение, приложение будет использовать системное сообщение вместе с вашим промптом. Это значение может отличаться от ваших собственных расчетов, так как с кадым вашим промптом может быть отправлена дополнительная информация.\nTotal - это общее количество токенов, существующих в текущем чате\nSent - это общее количество токенов, которые вы отправили\nReceived - это общее количество токенов, которые вы получили',
      'sent:': 'отправлено:',
      'received:': 'получено:',
      'Text size': 'Размер текста',
      'Include conversation': 'Включить разговор',
      'Add system message': 'Добавить системное сообщение',
      'Capture screenshot': 'Сделать скриншот',
      'You need to obtain Brave API key to use web search':
          'Вам нужно получить ключ API Brave для использования веб-поиска',
      'Settings->API and URLs': 'Настройки->API и URL',
      'Disable web search': 'Отключить веб-поиск',
      'Enable web search': 'Включить веб-поиск',
      'To prevent token overflows unnecessary cost we propose to limit the conversation length':
          'Чтобы предотвратить переполнение токенов и ненужные расходы, мы предлагаем ограничить длину разговора',
      'Max tokens to include': 'Максимальное количество токенов',
      'Min': 'Мин',
      'Med': 'Сред',
      'Hight': 'Выс',
      'Max': 'Макс',
      'Select items to include in system prompt':
          'Выберите элементы для системного промпта',
      'Knowledge about user': 'Знания о пользователе',
      'City name': 'Название города',
      'Weather': 'Погода',
      'User name': 'Имя пользователя',
      'Current timestamp': 'Текущая метка времени',
      'OS info': 'Информация о ОС',
      'Summarize conversation and populate the knowledge about the user':
          'Суммируйте разговор и заполните знания о пользователе',
      'Use memory about the user': 'Использовать память о пользователе',
      'Auto play messages from ai':
          'Автоматическое воспроизведение сообщений от ИИ',
      'Will ask AI to produce buttons for each response. It will consume additional tokens in order to generate suggestions':
          'Попросит ИИ создать кнопки для каждого ответа. Это потребует дополнительных токенов для генерации предложений',
      'Do you want to enable suggestion helpers?':
          'Хотите включить помощников по предложениям?',
      'Enable': 'Включить',
      'No. Don\'t show again': 'Нет. Больше не показывать',
      'Choose code block': 'Выберите блок кода',
      'Dismiss': 'Закрыть',
      'Use "/" for commands or type your message here':
          'Используйте "/" для команд или введите ваше сообщение здесь',
      'Settings': 'Настройки',
      'General': 'Общие',
      'Appearance': 'Внешний вид',
      'Tools': 'Инструменты',
      'User info': 'Информация о пользователе',
      'API and URLs': 'API и URL',
      'On response': 'На ответ',
      'Quick prompts': 'Быстрые промпты',
      'Overlay': 'Наложение',
      'Storage': 'Хранилище',
      'Hotkeys': 'Горячие клавиши',
      'About': 'О приложении',
      'Open the window keybinding': 'Привязка клавиш для открытия окна',
      'Open the window': 'Открыть окно',
      'Take a screenshot keybinding': 'Привязка клавиш для скриншота',
      'Use visual AI': 'Использовать визуальный ИИ',
      '[Not set]': '[Не установлено]',
      'Push-to-talk with screenshot': 'Нажмите для разговора со скриншотом',
      'Push-to-talk': 'Нажмите для разговора',
      'Show all keybindings': 'Показать все привязки клавиш',
      'Application storage location': 'Местоположение хранилища приложения',
      'Delete temp cache? Size:': 'Удалить временный кэш? Размер:',
      'Clear all data': 'Очистить все данные',
      'Overlay settings': 'Настройки наложения',
      'Enable overlay': 'Включить наложение',
      'Show settings icon in overlay': 'Показать значок настроек в наложении',
      'Adaptive': 'Адаптивный',
      'Show suggestions after ai response':
          'Показывать предложения после ответа ИИ',
      'Brave API key (search engine) \$':
          'Ключ API Brave (поисковая система) \$',
      'Text-to-Speech service:': 'Служба преобразования текста в речь:',
      'Global system prompt': 'Глобальная системный промпт',
      'Customizable Global system prompt will be used for all NEW chats. To check the whole system prompt press button below':
          'Глобавльный системный промпт будет использоваться для всех НОВЫХ чатов. Чтобы проверить весь системный промпт, нажмите кнопку ниже',
      'Click here to check the whole system prompt':
          'Нажмите здесь, чтобы посмотреть весь промпт',
      'Use ai to name chat': 'Использовать ИИ для названия чата',
      'Can cause additional charges!': 'Может вызвать дополнительные расходы!',
      'Audio and Microphone': 'Аудио и микрофон',
      'Locale': 'Локаль',
      'Launch at startup': 'Запуск при старте',
      'Prevent close app': 'Предотвратить закрытие приложения',
      'Show app in dock': 'Показать приложение в доке',
      'Hide window title': 'Скрыть заголовок окна',
      'User city': 'Город пользователя',
      'Your name that will be used in the chat':
          'Ваше имя, которое будет использоваться в чате',
      'Your city name that will be used in the chat and to get weather':
          'Название вашего города, которое будет использоваться в чате и для получения погоды',
      'Include knowledge about user': 'Включить знания о пользователе',
      'Open info about User': 'Открыть информацию о пользователе',
      'Include user city name in system prompt':
          'Включить название города пользователя в системный промпт',
      'Include weather in system prompt': 'Включить погоду в системный промпт',
      'Include user name in system prompt':
          'Включить имя пользователя в системный промпт',
      'Include current date and time in system prompt':
          'Включить текущую дату и время в системный промпт',
      'Include system info in system prompt':
          'Включить информацию о системе в системный промпт',
      'Learn about the user after creating new chat \$\$':
          'Узнать о пользователе после создания нового чата \$\$',
      'Function tools \$\$': 'Функциональные инструменты \$\$',
      'Toggle All': 'Переключить все',
      'Auto copy to clipboard': 'Автоматическое копирование в буфер обмена',
      'Auto open url': 'Автоматическое открытие URL',
      'Generate images': 'Генерировать изображения',
      'Additional tools': 'Дополнительные инструменты',
      'Imgur (Used to upload your image to your private Imgur account and get image link)':
          'Imgur (Используется для загрузки вашего изображения в ваш личный аккаунт Imgur и получения ссылки на изображение)',
      'Image Search engines': 'Поисковые системы изображений',
      'Enable annoy mode': 'Включить режим раздражения',
      'Use timer and allow AI to write you. Can cause additional charges!':
          'Использовать таймер и позволить ИИ писать вам. Может вызвать дополнительные расходы!',
      'Accent Color': 'Цвет акцента',
      'Theme mode': 'Режим темы',
      'Light': 'Светлая',
      'Dark': 'Темная',
      'Background': 'Фон',
      'Use aero': 'Использовать Aero',
      'Use acrylic': 'Использовать акрил',
      'Use transparent': 'Использовать прозрачный',
      'Use mica': 'Использовать Mica',
      'Transparency': 'Прозрачность',
      'Set window as frameless': 'Установить окно без рамки',
      'Restart the app to apply changes':
          'Перезапустите приложение, чтобы применить изменения',
      'Message Text size': 'Размер текста сообщения',
      'Basic Message Text Size': 'Базовый размер текста сообщения',
      'Compact Message Text Size': 'Компактный размер текста сообщения',
      'Voice:': 'Голос:',
      'Read sample': 'Прочитать образец',
      'Weather in': 'Погода в',
      'More': 'Больше',
      'Edit': 'Редактировать',
      'Continue writing': 'Продолжи текст',
      'Explain this': 'Объясни это',
      'Summarize this': 'Суммируй это',
      'Check grammar': 'Проверь грамматику',
      'Improve writing': 'Улучши написание',
      'Translate': 'Перевести',
      'Answer with tags': 'Ответить с тегами',
      'Search': 'Поиск',
      'Search...': 'Поиск...',
      'Chat rooms': 'Чат комнаты',
      'Create new chat': 'Создать новый чат',
      'Create folder': 'Создать папку',
      'Deleted chats': 'Удаленные чаты',
      'Storage usage': 'Использование хранилища',
      'Refresh from disk': 'Обновить с диска',
      'Add new': 'Добавить',
    },
  };
}

extension I18nExtension on String {
  String get tr {
    final localization = currentLocalization.value;
    return localization[this] ?? this;
  }

  String trFallback(String fallback) {
    final localization = currentLocalization.value;
    return localization.containsKey(this) ? localization[this]! : fallback;
  }
}
